title: "cmd-eikana - Apple Silicon版"
description: 左右のコマンドキーで英数/かなを切り替えるmacOS用ユーティリティ
url: "https://cmd-eikana.net"
theme: minima
header_pages: []
plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /img/ogp.png
        alt: "cmd-eikana - Apple Silicon版"
